version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai-app-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ai-app-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ai_logs
    restart: unless-stopped

volumes:
  qdrant_storage:
    driver: local
  mongodb_data:
    driver: local 